# permissions to do edit hardwareclassificationcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardwareclassificationcontroller-editor-role
rules:
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassificationcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassificationcontrollers/status
  verbs:
  - get
  - patch
  - update
